# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='닉네임', max_length=30),
            preserve_default=False,
        ),
    ]
