# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 11:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=48)),
                ('intro', models.TextField(blank=True)),
                ('writer', models.CharField(max_length=36)),
                ('publisher', models.CharField(max_length=36)),
                ('publication', models.CharField(max_length=12)),
                ('original_price', models.CharField(max_length=12)),
                ('used_price', models.CharField(blank=True, max_length=12)),
                ('sell_price1', models.CharField(blank=True, max_length=12)),
                ('sell_price2', models.CharField(blank=True, max_length=12)),
                ('sell_price3', models.CharField(blank=True, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='BookLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('book_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_store.BookInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('book_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_store.BookInfo')),
            ],
        ),
        migrations.CreateModel(
            name='SellBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_price', models.CharField(max_length=12)),
                ('book_status', models.CharField(max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('book_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_store.BookInfo')),
            ],
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='book_like',
            field=models.ManyToManyField(related_name='like_books', through='book_store.BookLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
