# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 15:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookBucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_store.BookInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='booklike',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='sellbook',
            old_name='author',
            new_name='user',
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='book_bucket',
            field=models.ManyToManyField(related_name='book_bucket', through='book_store.BookBucket', to=settings.AUTH_USER_MODEL),
        ),
    ]
