# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 16:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_store', '0002_auto_20170726_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_price', models.CharField(max_length=12)),
                ('book_status', models.CharField(max_length=2)),
                ('book_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_store.BookInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
