# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_store', '0003_sellbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('image_url', models.URLField(verbose_name='이미지url')),
                ('title', models.CharField(max_length=48, verbose_name='제목')),
                ('intro', models.TextField(blank=True, verbose_name='소개')),
                ('writer', models.CharField(max_length=36, verbose_name='저자')),
                ('price', models.IntegerField(verbose_name='정가')),
                ('isbn', models.CharField(max_length=100, unique=True, verbose_name='isbn')),
                ('publisher', models.CharField(max_length=40, verbose_name='출판사')),
                ('publication_date', models.DateField(verbose_name='출판일')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookBuyBucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_store.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookSellBucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_store.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('is_successed', models.BooleanField(default=False, verbose_name='거래성사')),
                ('sell_price', models.IntegerField(verbose_name='판매가')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_store.Book')),
                ('buyer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_set', to=settings.AUTH_USER_MODEL, verbose_name='구매자')),
                ('seller', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_set', to=settings.AUTH_USER_MODEL, verbose_name='판매자')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='bookbucket',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookbucket',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bookinfo',
            name='book_bucket',
        ),
        migrations.RemoveField(
            model_name='bookinfo',
            name='book_like',
        ),
        migrations.RemoveField(
            model_name='sellbook',
            name='book_info',
        ),
        migrations.RemoveField(
            model_name='sellbook',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='booklike',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created')},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created')},
        ),
        migrations.RemoveField(
            model_name='booklike',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='modify_at',
        ),
        migrations.AddField(
            model_name='booklike',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booklike',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='comment',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='booklike',
            name='book_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_store.Book'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='book_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_store.Book'),
        ),
        migrations.DeleteModel(
            name='BookBucket',
        ),
        migrations.DeleteModel(
            name='BookInfo',
        ),
        migrations.DeleteModel(
            name='SellBook',
        ),
    ]
