# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0004_auto_20170805_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sell_price',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='판매가'),
        ),
    ]
