# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0005_auto_20170805_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.CharField(max_length=240, verbose_name='이미지url'),
        ),
    ]
